### ISSUE TITLE
list of updates for simplewebrtc 2.x

### ISSUE THREAD

**Issue by fippo** [andyet/SimpleWebRTC#352]
* [x] signalmaster socket.io upgrade -- https://github.com/andyet/signalmaster/pull/47
* [x] simplewebrtc socket.io upgrade -- https://github.com/andyet/SimpleWebRTC/pull/351
* [x] rtcpeerconnection getstats -- https://github.com/andyet/SimpleWebRTC/issues/324 and https://github.com/otalk/RTCPeerConnection/pull/55
* [x] bump deps (maybe we should use greenkeeper?) -- https://github.com/andyet/SimpleWebRTC/pull/350
* [x] get rid of legacy constraints -- https://github.com/andyet/SimpleWebRTC/pull/322
* [x] signal end-of-candidates -- https://github.com/andyet/SimpleWebRTC/pull/313
* [x] change obsolete defaults -- https://github.com/andyet/SimpleWebRTC/issues/329
* [ ] change ice servers to use .urls instead of .url (signalmaster issue; client will just pass through so no need to do it here)
* [x] update website and sample (latest2.js?) -- #355
* [ ] tell ops about cowboy'ed signalmaster running in screen and make that less-cowboy (@stongo @nlf)

anything else?

**Comment by fippo** [comment]
cc @legastero @xdumaine

**Comment by xdumaine** [comment]
Pipe dream maybe but launching 2.0 with a fresh set of docs would be great. If we can decide on a format I can put a day into it.

**Comment by xdumaine** [comment]
By format I mean syntax and organization for defining methods, events, options, etc. Also useful would be a FAQ.

**Comment by fippo** [comment]
we could reuse https://github.com/otalk/simplewebrtc.com which still looks pretty awesome thanks to @lynnandtonic ... but i prefer to spend my time on things like getting rid of JSEP ;-)

**Comment by fippo** [comment]
starting merge now...

**Comment by fippo** [comment]
all merged. Tests are still passing.

**Comment by fippo** [comment]
i think i'm done here.

**Comment by xdumaine** [comment]
You've been busy!
